---
- name: "install  web packages"
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - "{{ ansible_local.custom.package.web_package }}"
    - "{{ ansible_local.custom.package.db_bpackage }}"
    - "{{ssl}}"

- name: " create ansible dir in document root an ssl dir in etc "
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{dir_html}}"
    - "{{dir_ansible}}"
    - "{{dir_ssl}}"

- name: "set hostname hostnamectl set-hostname "
  hostname:
    name: "{{set_hostname}}"

- name: "Generate index html"
  copy:
    content: " <H1> Learnining Ansible </H1>"
    dest: "{{dir_html}}/index.html"

- name: "copy ssl cer to aws"
  unarchive:
    src: server.tar
    dest: "{{dir_ssl}}"
  tags: copyssl

- name: " copy jinja2 file"
  template:
    src: vhost.j2
    dest: "{{dir_ansiblej2}}"
  notify:
    - restartservice


- name: " start the httpd and mariadb service"
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
    - "{{ ansible_local.custom.service.web_service}}"
    - "{{ ansible_local.custom.service.db_service }}"
  tags: httpd_restart



