---
- hosts: lamp
  name: "EC2 config for user and sshd "
  gather_facts: true
  tasks:
    - name: create a user"
      user:
        name: venkat
        groups: wheel
        comment: "venkat reddy"
        expires: -1
        password: "{{ 'yvreddy123' | password_hash( 'sha512', 'A512') }}"

    - name: "setup sudo access"
      copy:
        dest: /etc/sudoers.d/venkat
        content: "venkat ALL=(ALL) NOPASSWD:ALL "
        validate: /usr/sbin/visudo -cf %s

# remove or add comments - select the block CTRL /
#    - name: Allow 'wheel' group to have passwordless sudo
#      lineinfile:
#        dest: /etc/sudoers
#        state: present
#        line: 'venkat    ALL=(ALL)   NOPASSWD: ALL'
#        insertafter: '# %wheel        ALL=(ALL)       NOPASSWD: ALL'
#        validate: /usr/sbin/visudo -cf %s

    - name: "install required software in EC2"
      yum:
        name:
          - tree
        state: present

    - name: "backup sshd_config"
      copy:
        src: /etc/ssh/sshd_config
        dest: /home/venkat
        remote_src: yes

    - name: "copy ssh public keys to EC2 # key: source file path"
      authorized_key:
        user: venkat
        state: present
        key: "{{ lookup('file', '/home/hp/.ssh/id_rsa.pub') }}"
      tags: copysshkeys


    - name: "Password Authentication No "
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication no'
        state: absent
      notify:  restart_sshd

    - name: "Password Authentication Yes "
      lineinfile:
        path: /etc/ssh/sshd_config
        line: 'PasswordAuthentication yes'
        insertafter: '^#PasswordAuthentication yes'
        state: present
      notify: restart_sshd

  handlers:
    - name: restart_sshd
      service:
        name: sshd
        state: restarted