---
- hosts: all
  become: true
  tasks:
  - name: "Install packages"
    yum:
      name: "{{item}}"
      state: present
      update_cache: yes
    with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - firewalld

  - name: Add Docker repo
    get_url:
      url: "{{url_repo}}"
      dest: /etc/yum.repos.d/docer-ce.repo

  - name: "Install docker and its dependecies"
    yum:
      name: "{{item}}"
      state: present
      update_cache: yes
    with_items:
      - docker-ce
      - docker-ce-cli

  - name: " create docker"
    file:
      path: "{{dir_docker}}"
      state: directory

  - name: " copy daemon.json to /etc/docker "
    template:
      src: "{{daemon_json}}"
      dest: /etc/docker/daemon.json

  - name: " copy hosts to /etc/hosts "
    template:
      src: "{{etc_hosts}}"
      dest: /etc/hosts

  - name: "docker start"
    service:
      name: docker
      daemon_reload: true
      state: started
      enabled: true
  - name: "Firewalld start"
    service:
      name: firewalld
      state: started
      enabled: false






