---
- hosts: all
  become: true
  tasks:
    - name: "user add student"
      user:
        name: student
        group: wheel

    - name: " become su - student and run kudeadm init"
      command:
        cmd: kubeadm init --apiserver-advertise-address 192.168.33.13
      become: true
      become_method: su
      become_user: student
      changed_when: false

    - name: " Kudeadm init reset"
      command:
        cmd: kubeadm reset
      become: true
      become_method: su
      become_user: student
      changed_when: false







