---

- name: "install  php-mbstring php-xml"
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - php-mbstring
    - php-xml
- name: " start the httpd and mariadb service"
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
    - httpd
    - php-fpm
  tags: restart

#- name: "download the software phpmyadmin"
#  get_url:
#    url: "{{ download_phpmyadmin }}"
#    dest: " {{dir_html}} "
#    force: true
#  tags:
#    - download

- name: "create directory for phpMyAdmin"
  file:
    path: "{{dir_html}}/phpMyAdmin"
    state: directory
    owner: ec2-user
    group: apache
    mode: '755'
  tags:
    - dir

- name: download and unpack software
  unarchive:
    src: "{{ download_phpmyadmin }}"
    dest: /var/www/html/phpMyAdmin/
    remote_src: yes
    extra_opts: ['--strip-components=1']
    mode: "0755"
  tags:
    - unpack

- name: "remove tar.gz"
  file:
    path: "{{ dir_html }}/phpMyAdmin-latest-all-languages.tar.gz"
    state: absent