    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mongodb-deployment
      labels:
        app: mongodb
    spec:
     replicas: 1
     selector:
       matchLabels:
        app: mongodb
     template:
        metadata:
          labels:
            app: mongodb
        spec:
         containers:
         - name: mongodb
           image: mongo
           ports:
           - containerPort: 27017
           env: 
           - name: MONGO_INITDB_ROOT_USERNAME
             valueFrom:
               secretKeyRef:
                 name: mongodb-secret
                 key: mongodb_User
           - name: MONGO_INITDB_ROOT_PASSWORD
             valueFrom:   
               secretKeyRef:
                 name: mongodb-secret
                 key: mongodb_Password
---
apiVersion: v1
kind: Service
metadata:
 name: mongodb-service
spec:
 selector:
   app: mongodb
 ports:
 - protocol: TCP
   targetPort: 27017
   port: 27017

